// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ns1

import (
	"reflect"

	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type APIKey struct {
	pulumi.CustomResourceState

	// Whether the apikey can modify account settings.
	AccountManageAccountSettings pulumi.BoolPtrOutput `pulumi:"accountManageAccountSettings"`
	// Whether the apikey can modify account apikeys.
	AccountManageApikeys pulumi.BoolPtrOutput `pulumi:"accountManageApikeys"`
	// Whether the apikey can modify account payment methods.
	AccountManagePaymentMethods pulumi.BoolPtrOutput `pulumi:"accountManagePaymentMethods"`
	// Whether the apikey can modify the account plan.
	AccountManagePlan pulumi.BoolPtrOutput `pulumi:"accountManagePlan"`
	// Whether the apikey can modify other teams in the account.
	AccountManageTeams pulumi.BoolPtrOutput `pulumi:"accountManageTeams"`
	// Whether the apikey can modify account users.
	AccountManageUsers pulumi.BoolPtrOutput `pulumi:"accountManageUsers"`
	// Whether the apikey can view activity logs.
	AccountViewActivityLog pulumi.BoolPtrOutput `pulumi:"accountViewActivityLog"`
	// Whether the apikey can view invoices.
	AccountViewInvoices pulumi.BoolPtrOutput `pulumi:"accountViewInvoices"`
	// Whether the apikey can modify data feeds.
	DataManageDatafeeds pulumi.BoolPtrOutput `pulumi:"dataManageDatafeeds"`
	// Whether the apikey can modify data sources.
	DataManageDatasources pulumi.BoolPtrOutput `pulumi:"dataManageDatasources"`
	// Whether the apikey can publish to data feeds.
	DataPushToDatafeeds pulumi.BoolPtrOutput `pulumi:"dataPushToDatafeeds"`
	// Whether the apikey can manage DHCP.
	// Only relevant for the DDI product.
	DhcpManageDhcp pulumi.BoolPtrOutput `pulumi:"dhcpManageDhcp"`
	// Whether the apikey can view DHCP.
	// Only relevant for the DDI product.
	DhcpViewDhcp pulumi.BoolPtrOutput `pulumi:"dhcpViewDhcp"`
	// Whether the apikey can modify the accounts zones.
	DnsManageZones pulumi.BoolPtrOutput `pulumi:"dnsManageZones"`
	// Whether the apikey can view the accounts zones.
	DnsViewZones pulumi.BoolPtrOutput `pulumi:"dnsViewZones"`
	// If true, enable the `dnsZonesAllow` list, otherwise enable the `dnsZonesDeny` list.
	DnsZonesAllowByDefault pulumi.BoolPtrOutput `pulumi:"dnsZonesAllowByDefault"`
	// List of zones that the apikey may access.
	DnsZonesAllows pulumi.StringArrayOutput `pulumi:"dnsZonesAllows"`
	// List of zones that the apikey may not access.
	DnsZonesDenies pulumi.StringArrayOutput `pulumi:"dnsZonesDenies"`
	// Sets exclusivity on this IP whitelist.
	IpWhitelistStrict pulumi.BoolPtrOutput `pulumi:"ipWhitelistStrict"`
	// The IP addresses to whitelist for this key.
	IpWhitelists pulumi.StringArrayOutput `pulumi:"ipWhitelists"`
	// Whether the apikey can manage IPAM.
	// Only relevant for the DDI product.
	IpamManageIpam pulumi.BoolPtrOutput `pulumi:"ipamManageIpam"`
	// Whether the apikey can view IPAM.
	// Only relevant for the DDI product.
	IpamViewIpam pulumi.BoolPtrOutput `pulumi:"ipamViewIpam"`
	// The apikeys authentication token.
	Key pulumi.StringOutput `pulumi:"key"`
	// Whether the apikey can modify monitoring jobs.
	MonitoringManageJobs pulumi.BoolPtrOutput `pulumi:"monitoringManageJobs"`
	// Whether the apikey can modify notification lists.
	MonitoringManageLists pulumi.BoolPtrOutput `pulumi:"monitoringManageLists"`
	// Whether the apikey can view monitoring jobs.
	MonitoringViewJobs pulumi.BoolPtrOutput `pulumi:"monitoringViewJobs"`
	// The free form name of the apikey.
	Name pulumi.StringOutput `pulumi:"name"`
	// Whether the apikey can manage global active directory.
	// Only relevant for the DDI product.
	SecurityManageActiveDirectory pulumi.BoolPtrOutput `pulumi:"securityManageActiveDirectory"`
	// Whether the apikey can manage global two factor authentication.
	SecurityManageGlobal2fa pulumi.BoolPtrOutput `pulumi:"securityManageGlobal2fa"`
	// The teams that the apikey belongs to.
	Teams pulumi.StringArrayOutput `pulumi:"teams"`
}

// NewAPIKey registers a new resource with the given unique name, arguments, and options.
func NewAPIKey(ctx *pulumi.Context,
	name string, args *APIKeyArgs, opts ...pulumi.ResourceOption) (*APIKey, error) {
	if args == nil {
		args = &APIKeyArgs{}
	}
	var resource APIKey
	err := ctx.RegisterResource("ns1:index/aPIKey:APIKey", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAPIKey gets an existing APIKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAPIKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *APIKeyState, opts ...pulumi.ResourceOption) (*APIKey, error) {
	var resource APIKey
	err := ctx.ReadResource("ns1:index/aPIKey:APIKey", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering APIKey resources.
type apikeyState struct {
	// Whether the apikey can modify account settings.
	AccountManageAccountSettings *bool `pulumi:"accountManageAccountSettings"`
	// Whether the apikey can modify account apikeys.
	AccountManageApikeys *bool `pulumi:"accountManageApikeys"`
	// Whether the apikey can modify account payment methods.
	AccountManagePaymentMethods *bool `pulumi:"accountManagePaymentMethods"`
	// Whether the apikey can modify the account plan.
	AccountManagePlan *bool `pulumi:"accountManagePlan"`
	// Whether the apikey can modify other teams in the account.
	AccountManageTeams *bool `pulumi:"accountManageTeams"`
	// Whether the apikey can modify account users.
	AccountManageUsers *bool `pulumi:"accountManageUsers"`
	// Whether the apikey can view activity logs.
	AccountViewActivityLog *bool `pulumi:"accountViewActivityLog"`
	// Whether the apikey can view invoices.
	AccountViewInvoices *bool `pulumi:"accountViewInvoices"`
	// Whether the apikey can modify data feeds.
	DataManageDatafeeds *bool `pulumi:"dataManageDatafeeds"`
	// Whether the apikey can modify data sources.
	DataManageDatasources *bool `pulumi:"dataManageDatasources"`
	// Whether the apikey can publish to data feeds.
	DataPushToDatafeeds *bool `pulumi:"dataPushToDatafeeds"`
	// Whether the apikey can manage DHCP.
	// Only relevant for the DDI product.
	DhcpManageDhcp *bool `pulumi:"dhcpManageDhcp"`
	// Whether the apikey can view DHCP.
	// Only relevant for the DDI product.
	DhcpViewDhcp *bool `pulumi:"dhcpViewDhcp"`
	// Whether the apikey can modify the accounts zones.
	DnsManageZones *bool `pulumi:"dnsManageZones"`
	// Whether the apikey can view the accounts zones.
	DnsViewZones *bool `pulumi:"dnsViewZones"`
	// If true, enable the `dnsZonesAllow` list, otherwise enable the `dnsZonesDeny` list.
	DnsZonesAllowByDefault *bool `pulumi:"dnsZonesAllowByDefault"`
	// List of zones that the apikey may access.
	DnsZonesAllows []string `pulumi:"dnsZonesAllows"`
	// List of zones that the apikey may not access.
	DnsZonesDenies []string `pulumi:"dnsZonesDenies"`
	// Sets exclusivity on this IP whitelist.
	IpWhitelistStrict *bool `pulumi:"ipWhitelistStrict"`
	// The IP addresses to whitelist for this key.
	IpWhitelists []string `pulumi:"ipWhitelists"`
	// Whether the apikey can manage IPAM.
	// Only relevant for the DDI product.
	IpamManageIpam *bool `pulumi:"ipamManageIpam"`
	// Whether the apikey can view IPAM.
	// Only relevant for the DDI product.
	IpamViewIpam *bool `pulumi:"ipamViewIpam"`
	// The apikeys authentication token.
	Key *string `pulumi:"key"`
	// Whether the apikey can modify monitoring jobs.
	MonitoringManageJobs *bool `pulumi:"monitoringManageJobs"`
	// Whether the apikey can modify notification lists.
	MonitoringManageLists *bool `pulumi:"monitoringManageLists"`
	// Whether the apikey can view monitoring jobs.
	MonitoringViewJobs *bool `pulumi:"monitoringViewJobs"`
	// The free form name of the apikey.
	Name *string `pulumi:"name"`
	// Whether the apikey can manage global active directory.
	// Only relevant for the DDI product.
	SecurityManageActiveDirectory *bool `pulumi:"securityManageActiveDirectory"`
	// Whether the apikey can manage global two factor authentication.
	SecurityManageGlobal2fa *bool `pulumi:"securityManageGlobal2fa"`
	// The teams that the apikey belongs to.
	Teams []string `pulumi:"teams"`
}

type APIKeyState struct {
	// Whether the apikey can modify account settings.
	AccountManageAccountSettings pulumi.BoolPtrInput
	// Whether the apikey can modify account apikeys.
	AccountManageApikeys pulumi.BoolPtrInput
	// Whether the apikey can modify account payment methods.
	AccountManagePaymentMethods pulumi.BoolPtrInput
	// Whether the apikey can modify the account plan.
	AccountManagePlan pulumi.BoolPtrInput
	// Whether the apikey can modify other teams in the account.
	AccountManageTeams pulumi.BoolPtrInput
	// Whether the apikey can modify account users.
	AccountManageUsers pulumi.BoolPtrInput
	// Whether the apikey can view activity logs.
	AccountViewActivityLog pulumi.BoolPtrInput
	// Whether the apikey can view invoices.
	AccountViewInvoices pulumi.BoolPtrInput
	// Whether the apikey can modify data feeds.
	DataManageDatafeeds pulumi.BoolPtrInput
	// Whether the apikey can modify data sources.
	DataManageDatasources pulumi.BoolPtrInput
	// Whether the apikey can publish to data feeds.
	DataPushToDatafeeds pulumi.BoolPtrInput
	// Whether the apikey can manage DHCP.
	// Only relevant for the DDI product.
	DhcpManageDhcp pulumi.BoolPtrInput
	// Whether the apikey can view DHCP.
	// Only relevant for the DDI product.
	DhcpViewDhcp pulumi.BoolPtrInput
	// Whether the apikey can modify the accounts zones.
	DnsManageZones pulumi.BoolPtrInput
	// Whether the apikey can view the accounts zones.
	DnsViewZones pulumi.BoolPtrInput
	// If true, enable the `dnsZonesAllow` list, otherwise enable the `dnsZonesDeny` list.
	DnsZonesAllowByDefault pulumi.BoolPtrInput
	// List of zones that the apikey may access.
	DnsZonesAllows pulumi.StringArrayInput
	// List of zones that the apikey may not access.
	DnsZonesDenies pulumi.StringArrayInput
	// Sets exclusivity on this IP whitelist.
	IpWhitelistStrict pulumi.BoolPtrInput
	// The IP addresses to whitelist for this key.
	IpWhitelists pulumi.StringArrayInput
	// Whether the apikey can manage IPAM.
	// Only relevant for the DDI product.
	IpamManageIpam pulumi.BoolPtrInput
	// Whether the apikey can view IPAM.
	// Only relevant for the DDI product.
	IpamViewIpam pulumi.BoolPtrInput
	// The apikeys authentication token.
	Key pulumi.StringPtrInput
	// Whether the apikey can modify monitoring jobs.
	MonitoringManageJobs pulumi.BoolPtrInput
	// Whether the apikey can modify notification lists.
	MonitoringManageLists pulumi.BoolPtrInput
	// Whether the apikey can view monitoring jobs.
	MonitoringViewJobs pulumi.BoolPtrInput
	// The free form name of the apikey.
	Name pulumi.StringPtrInput
	// Whether the apikey can manage global active directory.
	// Only relevant for the DDI product.
	SecurityManageActiveDirectory pulumi.BoolPtrInput
	// Whether the apikey can manage global two factor authentication.
	SecurityManageGlobal2fa pulumi.BoolPtrInput
	// The teams that the apikey belongs to.
	Teams pulumi.StringArrayInput
}

func (APIKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*apikeyState)(nil)).Elem()
}

type apikeyArgs struct {
	// Whether the apikey can modify account settings.
	AccountManageAccountSettings *bool `pulumi:"accountManageAccountSettings"`
	// Whether the apikey can modify account apikeys.
	AccountManageApikeys *bool `pulumi:"accountManageApikeys"`
	// Whether the apikey can modify account payment methods.
	AccountManagePaymentMethods *bool `pulumi:"accountManagePaymentMethods"`
	// Whether the apikey can modify the account plan.
	AccountManagePlan *bool `pulumi:"accountManagePlan"`
	// Whether the apikey can modify other teams in the account.
	AccountManageTeams *bool `pulumi:"accountManageTeams"`
	// Whether the apikey can modify account users.
	AccountManageUsers *bool `pulumi:"accountManageUsers"`
	// Whether the apikey can view activity logs.
	AccountViewActivityLog *bool `pulumi:"accountViewActivityLog"`
	// Whether the apikey can view invoices.
	AccountViewInvoices *bool `pulumi:"accountViewInvoices"`
	// Whether the apikey can modify data feeds.
	DataManageDatafeeds *bool `pulumi:"dataManageDatafeeds"`
	// Whether the apikey can modify data sources.
	DataManageDatasources *bool `pulumi:"dataManageDatasources"`
	// Whether the apikey can publish to data feeds.
	DataPushToDatafeeds *bool `pulumi:"dataPushToDatafeeds"`
	// Whether the apikey can manage DHCP.
	// Only relevant for the DDI product.
	DhcpManageDhcp *bool `pulumi:"dhcpManageDhcp"`
	// Whether the apikey can view DHCP.
	// Only relevant for the DDI product.
	DhcpViewDhcp *bool `pulumi:"dhcpViewDhcp"`
	// Whether the apikey can modify the accounts zones.
	DnsManageZones *bool `pulumi:"dnsManageZones"`
	// Whether the apikey can view the accounts zones.
	DnsViewZones *bool `pulumi:"dnsViewZones"`
	// If true, enable the `dnsZonesAllow` list, otherwise enable the `dnsZonesDeny` list.
	DnsZonesAllowByDefault *bool `pulumi:"dnsZonesAllowByDefault"`
	// List of zones that the apikey may access.
	DnsZonesAllows []string `pulumi:"dnsZonesAllows"`
	// List of zones that the apikey may not access.
	DnsZonesDenies []string `pulumi:"dnsZonesDenies"`
	// Sets exclusivity on this IP whitelist.
	IpWhitelistStrict *bool `pulumi:"ipWhitelistStrict"`
	// The IP addresses to whitelist for this key.
	IpWhitelists []string `pulumi:"ipWhitelists"`
	// Whether the apikey can manage IPAM.
	// Only relevant for the DDI product.
	IpamManageIpam *bool `pulumi:"ipamManageIpam"`
	// Whether the apikey can view IPAM.
	// Only relevant for the DDI product.
	IpamViewIpam *bool `pulumi:"ipamViewIpam"`
	// Whether the apikey can modify monitoring jobs.
	MonitoringManageJobs *bool `pulumi:"monitoringManageJobs"`
	// Whether the apikey can modify notification lists.
	MonitoringManageLists *bool `pulumi:"monitoringManageLists"`
	// Whether the apikey can view monitoring jobs.
	MonitoringViewJobs *bool `pulumi:"monitoringViewJobs"`
	// The free form name of the apikey.
	Name *string `pulumi:"name"`
	// Whether the apikey can manage global active directory.
	// Only relevant for the DDI product.
	SecurityManageActiveDirectory *bool `pulumi:"securityManageActiveDirectory"`
	// Whether the apikey can manage global two factor authentication.
	SecurityManageGlobal2fa *bool `pulumi:"securityManageGlobal2fa"`
	// The teams that the apikey belongs to.
	Teams []string `pulumi:"teams"`
}

// The set of arguments for constructing a APIKey resource.
type APIKeyArgs struct {
	// Whether the apikey can modify account settings.
	AccountManageAccountSettings pulumi.BoolPtrInput
	// Whether the apikey can modify account apikeys.
	AccountManageApikeys pulumi.BoolPtrInput
	// Whether the apikey can modify account payment methods.
	AccountManagePaymentMethods pulumi.BoolPtrInput
	// Whether the apikey can modify the account plan.
	AccountManagePlan pulumi.BoolPtrInput
	// Whether the apikey can modify other teams in the account.
	AccountManageTeams pulumi.BoolPtrInput
	// Whether the apikey can modify account users.
	AccountManageUsers pulumi.BoolPtrInput
	// Whether the apikey can view activity logs.
	AccountViewActivityLog pulumi.BoolPtrInput
	// Whether the apikey can view invoices.
	AccountViewInvoices pulumi.BoolPtrInput
	// Whether the apikey can modify data feeds.
	DataManageDatafeeds pulumi.BoolPtrInput
	// Whether the apikey can modify data sources.
	DataManageDatasources pulumi.BoolPtrInput
	// Whether the apikey can publish to data feeds.
	DataPushToDatafeeds pulumi.BoolPtrInput
	// Whether the apikey can manage DHCP.
	// Only relevant for the DDI product.
	DhcpManageDhcp pulumi.BoolPtrInput
	// Whether the apikey can view DHCP.
	// Only relevant for the DDI product.
	DhcpViewDhcp pulumi.BoolPtrInput
	// Whether the apikey can modify the accounts zones.
	DnsManageZones pulumi.BoolPtrInput
	// Whether the apikey can view the accounts zones.
	DnsViewZones pulumi.BoolPtrInput
	// If true, enable the `dnsZonesAllow` list, otherwise enable the `dnsZonesDeny` list.
	DnsZonesAllowByDefault pulumi.BoolPtrInput
	// List of zones that the apikey may access.
	DnsZonesAllows pulumi.StringArrayInput
	// List of zones that the apikey may not access.
	DnsZonesDenies pulumi.StringArrayInput
	// Sets exclusivity on this IP whitelist.
	IpWhitelistStrict pulumi.BoolPtrInput
	// The IP addresses to whitelist for this key.
	IpWhitelists pulumi.StringArrayInput
	// Whether the apikey can manage IPAM.
	// Only relevant for the DDI product.
	IpamManageIpam pulumi.BoolPtrInput
	// Whether the apikey can view IPAM.
	// Only relevant for the DDI product.
	IpamViewIpam pulumi.BoolPtrInput
	// Whether the apikey can modify monitoring jobs.
	MonitoringManageJobs pulumi.BoolPtrInput
	// Whether the apikey can modify notification lists.
	MonitoringManageLists pulumi.BoolPtrInput
	// Whether the apikey can view monitoring jobs.
	MonitoringViewJobs pulumi.BoolPtrInput
	// The free form name of the apikey.
	Name pulumi.StringPtrInput
	// Whether the apikey can manage global active directory.
	// Only relevant for the DDI product.
	SecurityManageActiveDirectory pulumi.BoolPtrInput
	// Whether the apikey can manage global two factor authentication.
	SecurityManageGlobal2fa pulumi.BoolPtrInput
	// The teams that the apikey belongs to.
	Teams pulumi.StringArrayInput
}

func (APIKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*apikeyArgs)(nil)).Elem()
}
