// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ns1

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-ns1/sdk/v3/go/ns1/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Provides details about NS1 Networks. Use this if you would simply like to read
// information from NS1 into your configurations. For read/write operations, you
// should use a resource.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-ns1/sdk/v3/go/ns1"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Get details about NS1 Networks.
//			_, err := ns1.GetNetworks(ctx, nil, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetNetworks(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetNetworksResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetNetworksResult
	err := ctx.Invoke("ns1:index/getNetworks:getNetworks", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getNetworks.
type GetNetworksResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// A set of the available networks. Networks is
	// documented below.
	Networks []GetNetworksNetwork `pulumi:"networks"`
}

func GetNetworksOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) GetNetworksResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (GetNetworksResultOutput, error) {
		opts = internal.PkgInvokeDefaultOpts(opts)
		var rv GetNetworksResult
		secret, err := ctx.InvokePackageRaw("ns1:index/getNetworks:getNetworks", nil, &rv, "", opts...)
		if err != nil {
			return GetNetworksResultOutput{}, err
		}

		output := pulumi.ToOutput(rv).(GetNetworksResultOutput)
		if secret {
			return pulumi.ToSecret(output).(GetNetworksResultOutput), nil
		}
		return output, nil
	}).(GetNetworksResultOutput)
}

// A collection of values returned by getNetworks.
type GetNetworksResultOutput struct{ *pulumi.OutputState }

func (GetNetworksResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNetworksResult)(nil)).Elem()
}

func (o GetNetworksResultOutput) ToGetNetworksResultOutput() GetNetworksResultOutput {
	return o
}

func (o GetNetworksResultOutput) ToGetNetworksResultOutputWithContext(ctx context.Context) GetNetworksResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetNetworksResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetworksResult) string { return v.Id }).(pulumi.StringOutput)
}

// A set of the available networks. Networks is
// documented below.
func (o GetNetworksResultOutput) Networks() GetNetworksNetworkArrayOutput {
	return o.ApplyT(func(v GetNetworksResult) []GetNetworksNetwork { return v.Networks }).(GetNetworksNetworkArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetNetworksResultOutput{})
}
