provider: ns1
major-version: 3
env:
  NS1_APIKEY: ${{ secrets.NS1_APIKEY }}
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
plugins:
  - name: terraform
    version: "1.0.16"
    kind: converter
