provider: ns1
major-version: 3
env:
    NS1_APIKEY: ${{ secrets.NS1_APIKEY }}
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
registryDocs: true
plugins:
    - name: std
      version: "1.6.2"
    - name: external
      version: "0.0.6"
    - name: terraform
      version: "1.0.16"
      kind: converter
esc:
    enabled: true
