// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ns1
{
    public static class GetDNSSec
    {
        /// <summary>
        /// Provides DNSSEC details about a NS1 Zone.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Ns1 = Pulumi.Ns1;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Get DNSSEC details about a NS1 Zone.
        ///     var exampleZone = new Ns1.Zone("exampleZone", new()
        ///     {
        ///         Dnssec = true,
        ///         ZoneName = "terraform.example.io",
        ///     });
        /// 
        ///     var exampleDNSSec = Ns1.GetDNSSec.Invoke(new()
        ///     {
        ///         Zone = exampleZone.ZoneName,
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetDNSSecResult> InvokeAsync(GetDNSSecArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDNSSecResult>("ns1:index/getDNSSec:getDNSSec", args ?? new GetDNSSecArgs(), options.WithDefaults());

        /// <summary>
        /// Provides DNSSEC details about a NS1 Zone.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Ns1 = Pulumi.Ns1;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Get DNSSEC details about a NS1 Zone.
        ///     var exampleZone = new Ns1.Zone("exampleZone", new()
        ///     {
        ///         Dnssec = true,
        ///         ZoneName = "terraform.example.io",
        ///     });
        /// 
        ///     var exampleDNSSec = Ns1.GetDNSSec.Invoke(new()
        ///     {
        ///         Zone = exampleZone.ZoneName,
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetDNSSecResult> Invoke(GetDNSSecInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDNSSecResult>("ns1:index/getDNSSec:getDNSSec", args ?? new GetDNSSecInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDNSSecArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the zone to get DNSSEC details for.
        /// </summary>
        [Input("zone", required: true)]
        public string Zone { get; set; } = null!;

        public GetDNSSecArgs()
        {
        }
        public static new GetDNSSecArgs Empty => new GetDNSSecArgs();
    }

    public sealed class GetDNSSecInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The name of the zone to get DNSSEC details for.
        /// </summary>
        [Input("zone", required: true)]
        public Input<string> Zone { get; set; } = null!;

        public GetDNSSecInvokeArgs()
        {
        }
        public static new GetDNSSecInvokeArgs Empty => new GetDNSSecInvokeArgs();
    }


    [OutputType]
    public sealed class GetDNSSecResult
    {
        /// <summary>
        /// (Computed) - Delegation field is documented
        /// below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetDNSSecDelegationResult> Delegations;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// (Computed) - Keys field is documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetDNSSecKeyResult> Keys;
        public readonly string Zone;

        [OutputConstructor]
        private GetDNSSecResult(
            ImmutableArray<Outputs.GetDNSSecDelegationResult> delegations,

            string id,

            ImmutableArray<Outputs.GetDNSSecKeyResult> keys,

            string zone)
        {
            Delegations = delegations;
            Id = id;
            Keys = keys;
            Zone = zone;
        }
    }
}
