// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ns1
{
    public static class GetNetworks
    {
        /// <summary>
        /// Provides details about NS1 Networks. Use this if you would simply like to read
        /// information from NS1 into your configurations. For read/write operations, you
        /// should use a resource.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Ns1 = Pulumi.Ns1;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Get details about NS1 Networks.
        ///     var example = Ns1.GetNetworks.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetNetworksResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetNetworksResult>("ns1:index/getNetworks:getNetworks", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Provides details about NS1 Networks. Use this if you would simply like to read
        /// information from NS1 into your configurations. For read/write operations, you
        /// should use a resource.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Ns1 = Pulumi.Ns1;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Get details about NS1 Networks.
        ///     var example = Ns1.GetNetworks.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetNetworksResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetNetworksResult>("ns1:index/getNetworks:getNetworks", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Provides details about NS1 Networks. Use this if you would simply like to read
        /// information from NS1 into your configurations. For read/write operations, you
        /// should use a resource.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Ns1 = Pulumi.Ns1;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     // Get details about NS1 Networks.
        ///     var example = Ns1.GetNetworks.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetNetworksResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetNetworksResult>("ns1:index/getNetworks:getNetworks", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetNetworksResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// A set of the available networks. Networks is
        /// documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetNetworksNetworkResult> Networks;

        [OutputConstructor]
        private GetNetworksResult(
            string id,

            ImmutableArray<Outputs.GetNetworksNetworkResult> networks)
        {
            Id = id;
            Networks = networks;
        }
    }
}
