// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ns1.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class APIKeySecretArgs extends com.pulumi.resources.ResourceArgs {

    public static final APIKeySecretArgs Empty = new APIKeySecretArgs();

    /**
     * Whether this secret is currently enabled for authentication.
     * 
     */
    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    /**
     * @return Whether this secret is currently enabled for authentication.
     * 
     */
    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * The expiration date/time of the secret in ISO 8601 format.
     * 
     */
    @Import(name="expiresAt")
    private @Nullable Output<String> expiresAt;

    /**
     * @return The expiration date/time of the secret in ISO 8601 format.
     * 
     */
    public Optional<Output<String>> expiresAt() {
        return Optional.ofNullable(this.expiresAt);
    }

    /**
     * The unique identifier for the secret.
     * 
     */
    @Import(name="id")
    private @Nullable Output<String> id;

    /**
     * @return The unique identifier for the secret.
     * 
     */
    public Optional<Output<String>> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * The last time this secret was used for authentication.
     * 
     */
    @Import(name="lastAccess")
    private @Nullable Output<String> lastAccess;

    /**
     * @return The last time this secret was used for authentication.
     * 
     */
    public Optional<Output<String>> lastAccess() {
        return Optional.ofNullable(this.lastAccess);
    }

    private APIKeySecretArgs() {}

    private APIKeySecretArgs(APIKeySecretArgs $) {
        this.enabled = $.enabled;
        this.expiresAt = $.expiresAt;
        this.id = $.id;
        this.lastAccess = $.lastAccess;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(APIKeySecretArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private APIKeySecretArgs $;

        public Builder() {
            $ = new APIKeySecretArgs();
        }

        public Builder(APIKeySecretArgs defaults) {
            $ = new APIKeySecretArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param enabled Whether this secret is currently enabled for authentication.
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Whether this secret is currently enabled for authentication.
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param expiresAt The expiration date/time of the secret in ISO 8601 format.
         * 
         * @return builder
         * 
         */
        public Builder expiresAt(@Nullable Output<String> expiresAt) {
            $.expiresAt = expiresAt;
            return this;
        }

        /**
         * @param expiresAt The expiration date/time of the secret in ISO 8601 format.
         * 
         * @return builder
         * 
         */
        public Builder expiresAt(String expiresAt) {
            return expiresAt(Output.of(expiresAt));
        }

        /**
         * @param id The unique identifier for the secret.
         * 
         * @return builder
         * 
         */
        public Builder id(@Nullable Output<String> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id The unique identifier for the secret.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            return id(Output.of(id));
        }

        /**
         * @param lastAccess The last time this secret was used for authentication.
         * 
         * @return builder
         * 
         */
        public Builder lastAccess(@Nullable Output<String> lastAccess) {
            $.lastAccess = lastAccess;
            return this;
        }

        /**
         * @param lastAccess The last time this secret was used for authentication.
         * 
         * @return builder
         * 
         */
        public Builder lastAccess(String lastAccess) {
            return lastAccess(Output.of(lastAccess));
        }

        public APIKeySecretArgs build() {
            return $;
        }
    }

}
