// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ns1.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetDNSSecArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetDNSSecArgs Empty = new GetDNSSecArgs();

    /**
     * The name of the zone to get DNSSEC details for.
     * 
     */
    @Import(name="zone", required=true)
    private Output<String> zone;

    /**
     * @return The name of the zone to get DNSSEC details for.
     * 
     */
    public Output<String> zone() {
        return this.zone;
    }

    private GetDNSSecArgs() {}

    private GetDNSSecArgs(GetDNSSecArgs $) {
        this.zone = $.zone;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetDNSSecArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetDNSSecArgs $;

        public Builder() {
            $ = new GetDNSSecArgs();
        }

        public Builder(GetDNSSecArgs defaults) {
            $ = new GetDNSSecArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param zone The name of the zone to get DNSSEC details for.
         * 
         * @return builder
         * 
         */
        public Builder zone(Output<String> zone) {
            $.zone = zone;
            return this;
        }

        /**
         * @param zone The name of the zone to get DNSSEC details for.
         * 
         * @return builder
         * 
         */
        public Builder zone(String zone) {
            return zone(Output.of(zone));
        }

        public GetDNSSecArgs build() {
            if ($.zone == null) {
                throw new MissingRequiredPropertyException("GetDNSSecArgs", "zone");
            }
            return $;
        }
    }

}
