// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ns1.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DatasetReport {
    private @Nullable Integer createdAt;
    private @Nullable Integer end;
    private @Nullable String id;
    private @Nullable Integer start;
    private @Nullable String status;

    private DatasetReport() {}
    public Optional<Integer> createdAt() {
        return Optional.ofNullable(this.createdAt);
    }
    public Optional<Integer> end() {
        return Optional.ofNullable(this.end);
    }
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }
    public Optional<Integer> start() {
        return Optional.ofNullable(this.start);
    }
    public Optional<String> status() {
        return Optional.ofNullable(this.status);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DatasetReport defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Integer createdAt;
        private @Nullable Integer end;
        private @Nullable String id;
        private @Nullable Integer start;
        private @Nullable String status;
        public Builder() {}
        public Builder(DatasetReport defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.createdAt = defaults.createdAt;
    	      this.end = defaults.end;
    	      this.id = defaults.id;
    	      this.start = defaults.start;
    	      this.status = defaults.status;
        }

        @CustomType.Setter
        public Builder createdAt(@Nullable Integer createdAt) {

            this.createdAt = createdAt;
            return this;
        }
        @CustomType.Setter
        public Builder end(@Nullable Integer end) {

            this.end = end;
            return this;
        }
        @CustomType.Setter
        public Builder id(@Nullable String id) {

            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder start(@Nullable Integer start) {

            this.start = start;
            return this;
        }
        @CustomType.Setter
        public Builder status(@Nullable String status) {

            this.status = status;
            return this;
        }
        public DatasetReport build() {
            final var _resultValue = new DatasetReport();
            _resultValue.createdAt = createdAt;
            _resultValue.end = end;
            _resultValue.id = id;
            _resultValue.start = start;
            _resultValue.status = status;
            return _resultValue;
        }
    }
}
