// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("ns1");

/**
 * The ns1 API key (required)
 */
export declare const apikey: string | undefined;
Object.defineProperty(exports, "apikey", {
    get() {
        return __config.get("apikey");
    },
    enumerable: true,
});

/**
 * URL prefix (including version) for API calls
 */
export declare const endpoint: string | undefined;
Object.defineProperty(exports, "endpoint", {
    get() {
        return __config.get("endpoint");
    },
    enumerable: true,
});

/**
 * Don't validate server SSL/TLS certificate
 */
export declare const ignoreSsl: boolean | undefined;
Object.defineProperty(exports, "ignoreSsl", {
    get() {
        return __config.getObject<boolean>("ignoreSsl");
    },
    enumerable: true,
});

/**
 * Tune response to rate limits, see docs
 */
export declare const rateLimitParallelism: number | undefined;
Object.defineProperty(exports, "rateLimitParallelism", {
    get() {
        return __config.getObject<number>("rateLimitParallelism");
    },
    enumerable: true,
});

/**
 * Maximum retries for 50x errors (-1 to disable)
 */
export declare const retryMax: number | undefined;
Object.defineProperty(exports, "retryMax", {
    get() {
        return __config.getObject<number>("retryMax");
    },
    enumerable: true,
});

/**
 * User-Agent string to use in NS1 API requests
 */
export declare const userAgent: string | undefined;
Object.defineProperty(exports, "userAgent", {
    get() {
        return __config.get("userAgent");
    },
    enumerable: true,
});

