// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ns1.Outputs
{

    [OutputType]
    public sealed class RecordRegion
    {
        public readonly ImmutableDictionary<string, string>? Meta;
        /// <summary>
        /// Name of the region (or Answer Group).
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private RecordRegion(
            ImmutableDictionary<string, string>? meta,

            string name)
        {
            Meta = meta;
            Name = name;
        }
    }
}
