// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ns1.Outputs
{

    [OutputType]
    public sealed class TeamDnsRecordsAllow
    {
        public readonly string Domain;
        public readonly bool IncludeSubdomains;
        public readonly string Type;
        public readonly string Zone;

        [OutputConstructor]
        private TeamDnsRecordsAllow(
            string domain,

            bool includeSubdomains,

            string type,

            string zone)
        {
            Domain = domain;
            IncludeSubdomains = includeSubdomains;
            Type = type;
            Zone = zone;
        }
    }
}
