// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ns1;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AccountWhitelistArgs extends com.pulumi.resources.ResourceArgs {

    public static final AccountWhitelistArgs Empty = new AccountWhitelistArgs();

    /**
     * The free form name of the whitelist.
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The free form name of the whitelist.
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Array of IP addresses/networks from which to allow access.
     * 
     */
    @Import(name="values", required=true)
    private Output<List<String>> values;

    /**
     * @return Array of IP addresses/networks from which to allow access.
     * 
     */
    public Output<List<String>> values() {
        return this.values;
    }

    private AccountWhitelistArgs() {}

    private AccountWhitelistArgs(AccountWhitelistArgs $) {
        this.name = $.name;
        this.values = $.values;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AccountWhitelistArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AccountWhitelistArgs $;

        public Builder() {
            $ = new AccountWhitelistArgs();
        }

        public Builder(AccountWhitelistArgs defaults) {
            $ = new AccountWhitelistArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The free form name of the whitelist.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The free form name of the whitelist.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param values Array of IP addresses/networks from which to allow access.
         * 
         * @return builder
         * 
         */
        public Builder values(Output<List<String>> values) {
            $.values = values;
            return this;
        }

        /**
         * @param values Array of IP addresses/networks from which to allow access.
         * 
         * @return builder
         * 
         */
        public Builder values(List<String> values) {
            return values(Output.of(values));
        }

        /**
         * @param values Array of IP addresses/networks from which to allow access.
         * 
         * @return builder
         * 
         */
        public Builder values(String... values) {
            return values(List.of(values));
        }

        public AccountWhitelistArgs build() {
            $.values = Objects.requireNonNull($.values, "expected parameter 'values' to be non-null");
            return $;
        }
    }

}
