// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ns1;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.ns1.AlertArgs;
import com.pulumi.ns1.Utilities;
import com.pulumi.ns1.inputs.AlertState;
import com.pulumi.ns1.outputs.AlertData;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Provides a NS1 Alert resource. This can be used to create, modify, and delete alerts.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.ns1.Alert;
 * import com.pulumi.ns1.AlertArgs;
 * import com.pulumi.ns1.inputs.AlertDataArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var exampleZoneAlert = new Alert("exampleZoneAlert", AlertArgs.builder()
 *             .name("Example Zone Alert")
 *             .type("zone")
 *             .subtype("transfer_failed")
 *             .notificationLists()
 *             .zoneNames(            
 *                 "a.b.c.com",
 *                 "myzone")
 *             .recordIds()
 *             .build());
 * 
 *         var exampleUsageAlert = new Alert("exampleUsageAlert", AlertArgs.builder()
 *             .name("Example Usage Alert")
 *             .type("account")
 *             .subtype("record_usage")
 *             .datas(AlertDataArgs.builder()
 *                 .alertAtPercent(80)
 *                 .build())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## NS1 Documentation
 * 
 * [Alerts Api Doc](https://ns1.com/api#alerts)
 * 
 * ## Import
 * 
 * ```sh
 * $ pulumi import ns1:index/alert:Alert &lt;name&gt; &lt;alert_id&gt;`
 * ```
 * 
 */
@ResourceType(type="ns1:index/alert:Alert")
public class Alert extends com.pulumi.resources.CustomResource {
    /**
     * (Read Only) The Unix timestamp representing when the alert configuration was created.
     * 
     */
    @Export(name="createdAt", refs={Integer.class}, tree="[0]")
    private Output<Integer> createdAt;

    /**
     * @return (Read Only) The Unix timestamp representing when the alert configuration was created.
     * 
     */
    public Output<Integer> createdAt() {
        return this.createdAt;
    }
    /**
     * (Read Only) The user or apikey that created this alert.
     * 
     */
    @Export(name="createdBy", refs={String.class}, tree="[0]")
    private Output<String> createdBy;

    /**
     * @return (Read Only) The user or apikey that created this alert.
     * 
     */
    public Output<String> createdBy() {
        return this.createdBy;
    }
    /**
     * A resource block with additional settings: the name and type of them vary based on the alert type.
     * 
     */
    @Export(name="datas", refs={List.class,AlertData.class}, tree="[0,1]")
    private Output</* @Nullable */ List<AlertData>> datas;

    /**
     * @return A resource block with additional settings: the name and type of them vary based on the alert type.
     * 
     */
    public Output<Optional<List<AlertData>>> datas() {
        return Codegen.optional(this.datas);
    }
    /**
     * The free-form display name for the alert.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The free-form display name for the alert.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * A list of id&#39;s for notification lists whose notifiers will be triggered by the alert.
     * 
     */
    @Export(name="notificationLists", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> notificationLists;

    /**
     * @return A list of id&#39;s for notification lists whose notifiers will be triggered by the alert.
     * 
     */
    public Output<Optional<List<String>>> notificationLists() {
        return Codegen.optional(this.notificationLists);
    }
    /**
     * A list of record id&#39;s this alert applies to.
     * 
     */
    @Export(name="recordIds", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> recordIds;

    /**
     * @return A list of record id&#39;s this alert applies to.
     * 
     */
    public Output<Optional<List<String>>> recordIds() {
        return Codegen.optional(this.recordIds);
    }
    /**
     * The type of the alert.
     * 
     */
    @Export(name="subtype", refs={String.class}, tree="[0]")
    private Output<String> subtype;

    /**
     * @return The type of the alert.
     * 
     */
    public Output<String> subtype() {
        return this.subtype;
    }
    /**
     * The type of the alert.
     * 
     */
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output<String> type;

    /**
     * @return The type of the alert.
     * 
     */
    public Output<String> type() {
        return this.type;
    }
    /**
     * (Read Only) The Unix timestamp representing when the alert configuration was last modified.
     * 
     */
    @Export(name="updatedAt", refs={Integer.class}, tree="[0]")
    private Output<Integer> updatedAt;

    /**
     * @return (Read Only) The Unix timestamp representing when the alert configuration was last modified.
     * 
     */
    public Output<Integer> updatedAt() {
        return this.updatedAt;
    }
    /**
     * (Read Only) The user or apikey that last modified this alert.
     * 
     */
    @Export(name="updatedBy", refs={String.class}, tree="[0]")
    private Output<String> updatedBy;

    /**
     * @return (Read Only) The user or apikey that last modified this alert.
     * 
     */
    public Output<String> updatedBy() {
        return this.updatedBy;
    }
    /**
     * A list of zones this alert applies to.
     * 
     */
    @Export(name="zoneNames", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> zoneNames;

    /**
     * @return A list of zones this alert applies to.
     * 
     */
    public Output<Optional<List<String>>> zoneNames() {
        return Codegen.optional(this.zoneNames);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Alert(java.lang.String name) {
        this(name, AlertArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Alert(java.lang.String name, AlertArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Alert(java.lang.String name, AlertArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("ns1:index/alert:Alert", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Alert(java.lang.String name, Output<java.lang.String> id, @Nullable AlertState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("ns1:index/alert:Alert", name, state, makeResourceOptions(options, id), false);
    }

    private static AlertArgs makeArgs(AlertArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? AlertArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Alert get(java.lang.String name, Output<java.lang.String> id, @Nullable AlertState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Alert(name, id, state, options);
    }
}
