// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ns1;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.ns1.inputs.DatasetDatatypeArgs;
import com.pulumi.ns1.inputs.DatasetRepeatArgs;
import com.pulumi.ns1.inputs.DatasetTimeframeArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DatasetArgs extends com.pulumi.resources.ResourceArgs {

    public static final DatasetArgs Empty = new DatasetArgs();

    @Import(name="datatype", required=true)
    private Output<DatasetDatatypeArgs> datatype;

    public Output<DatasetDatatypeArgs> datatype() {
        return this.datatype;
    }

    @Import(name="exportType", required=true)
    private Output<String> exportType;

    public Output<String> exportType() {
        return this.exportType;
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="recipientEmails")
    private @Nullable Output<List<String>> recipientEmails;

    public Optional<Output<List<String>>> recipientEmails() {
        return Optional.ofNullable(this.recipientEmails);
    }

    @Import(name="repeat")
    private @Nullable Output<DatasetRepeatArgs> repeat;

    public Optional<Output<DatasetRepeatArgs>> repeat() {
        return Optional.ofNullable(this.repeat);
    }

    @Import(name="timeframe", required=true)
    private Output<DatasetTimeframeArgs> timeframe;

    public Output<DatasetTimeframeArgs> timeframe() {
        return this.timeframe;
    }

    private DatasetArgs() {}

    private DatasetArgs(DatasetArgs $) {
        this.datatype = $.datatype;
        this.exportType = $.exportType;
        this.name = $.name;
        this.recipientEmails = $.recipientEmails;
        this.repeat = $.repeat;
        this.timeframe = $.timeframe;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DatasetArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DatasetArgs $;

        public Builder() {
            $ = new DatasetArgs();
        }

        public Builder(DatasetArgs defaults) {
            $ = new DatasetArgs(Objects.requireNonNull(defaults));
        }

        public Builder datatype(Output<DatasetDatatypeArgs> datatype) {
            $.datatype = datatype;
            return this;
        }

        public Builder datatype(DatasetDatatypeArgs datatype) {
            return datatype(Output.of(datatype));
        }

        public Builder exportType(Output<String> exportType) {
            $.exportType = exportType;
            return this;
        }

        public Builder exportType(String exportType) {
            return exportType(Output.of(exportType));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder recipientEmails(@Nullable Output<List<String>> recipientEmails) {
            $.recipientEmails = recipientEmails;
            return this;
        }

        public Builder recipientEmails(List<String> recipientEmails) {
            return recipientEmails(Output.of(recipientEmails));
        }

        public Builder recipientEmails(String... recipientEmails) {
            return recipientEmails(List.of(recipientEmails));
        }

        public Builder repeat(@Nullable Output<DatasetRepeatArgs> repeat) {
            $.repeat = repeat;
            return this;
        }

        public Builder repeat(DatasetRepeatArgs repeat) {
            return repeat(Output.of(repeat));
        }

        public Builder timeframe(Output<DatasetTimeframeArgs> timeframe) {
            $.timeframe = timeframe;
            return this;
        }

        public Builder timeframe(DatasetTimeframeArgs timeframe) {
            return timeframe(Output.of(timeframe));
        }

        public DatasetArgs build() {
            if ($.datatype == null) {
                throw new MissingRequiredPropertyException("DatasetArgs", "datatype");
            }
            if ($.exportType == null) {
                throw new MissingRequiredPropertyException("DatasetArgs", "exportType");
            }
            if ($.timeframe == null) {
                throw new MissingRequiredPropertyException("DatasetArgs", "timeframe");
            }
            return $;
        }
    }

}
