// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ns1.Inputs
{

    public sealed class PulsarJobWeightGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("defaultValue", required: true)]
        public Input<double> DefaultValue { get; set; } = null!;

        [Input("maximize")]
        public Input<bool>? Maximize { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("weight", required: true)]
        public Input<int> Weight { get; set; } = null!;

        public PulsarJobWeightGetArgs()
        {
        }
        public static new PulsarJobWeightGetArgs Empty => new PulsarJobWeightGetArgs();
    }
}
