// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provides details about NS1 Networks. Use this if you would simply like to read
 * information from NS1 into your configurations. For read/write operations, you
 * should use a resource.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ns1 from "@pulumi/ns1";
 *
 * // Get details about NS1 Networks.
 * const example = ns1.getNetworks({});
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getNetworks(opts?: pulumi.InvokeOptions): Promise<GetNetworksResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ns1:index/getNetworks:getNetworks", {
    }, opts);
}

/**
 * A collection of values returned by getNetworks.
 */
export interface GetNetworksResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * A set of the available networks. Networks is
     * documented below.
     */
    readonly networks: outputs.GetNetworksNetwork[];
}
/**
 * Provides details about NS1 Networks. Use this if you would simply like to read
 * information from NS1 into your configurations. For read/write operations, you
 * should use a resource.
 *
 * ## Example Usage
 *
 * <!--Start PulumiCodeChooser -->
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ns1 from "@pulumi/ns1";
 *
 * // Get details about NS1 Networks.
 * const example = ns1.getNetworks({});
 * ```
 * <!--End PulumiCodeChooser -->
 */
export function getNetworksOutput(opts?: pulumi.InvokeOptions): pulumi.Output<GetNetworksResult> {
    return pulumi.output(getNetworks(opts))
}
