// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provides details about a NS1 Zone. Use this if you would simply like to read
 * information from NS1 into your configurations. For read/write operations, you
 * should use a resource.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ns1 from "@pulumi/ns1";
 *
 * // Get details about a NS1 Zone.
 * const example = pulumi.output(ns1.getZone({
 *     zone: "terraform.example.io",
 * }, { async: true }));
 * ```
 */
export function getZone(args: GetZoneArgs, opts?: pulumi.InvokeOptions): Promise<GetZoneResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("ns1:index/getZone:getZone", {
        "additionalPrimaries": args.additionalPrimaries,
        "zone": args.zone,
    }, opts);
}

/**
 * A collection of arguments for invoking getZone.
 */
export interface GetZoneArgs {
    /**
     * List of additional IPv4 addresses for the primary
     * zone.
     */
    readonly additionalPrimaries?: string[];
    /**
     * The domain name of the zone.
     */
    readonly zone: string;
}

/**
 * A collection of values returned by getZone.
 */
export interface GetZoneResult {
    /**
     * List of additional IPv4 addresses for the primary
     * zone.
     */
    readonly additionalPrimaries?: string[];
    /**
     * Authoritative Name Servers.
     */
    readonly dnsServers: string;
    /**
     * Whether or not DNSSEC is enabled for the zone.
     */
    readonly dnssec: boolean;
    /**
     * The SOA Expiry.
     */
    readonly expiry: number;
    /**
     * The SOA Hostmaster.
     */
    readonly hostmaster: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The linked target zone.
     */
    readonly link: string;
    /**
     * List of network IDs (`int`) for which the zone should be made
     * available. Default is network 0, the primary NSONE Global Network.
     */
    readonly networks: number[];
    /**
     * The SOA NX TTL.
     */
    readonly nxTtl: number;
    /**
     * The primary zones' IPv4 address.
     */
    readonly primary: string;
    /**
     * The SOA Refresh.
     */
    readonly refresh: number;
    /**
     * The SOA Retry.
     */
    readonly retry: number;
    /**
     * List of secondary servers. Secondaries is
     * documented below.
     */
    readonly secondaries: outputs.GetZoneSecondary[];
    /**
     * The SOA TTL.
     */
    readonly ttl: number;
    readonly zone: string;
}
