// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class User extends pulumi.CustomResource {
    /**
     * Get an existing User resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: UserState, opts?: pulumi.CustomResourceOptions): User {
        return new User(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ns1:index/user:User';

    /**
     * Returns true if the given object is an instance of User.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is User {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === User.__pulumiType;
    }

    /**
     * Whether the user can modify account settings.
     */
    public readonly accountManageAccountSettings!: pulumi.Output<boolean | undefined>;
    /**
     * Whether the user can modify account apikeys.
     */
    public readonly accountManageApikeys!: pulumi.Output<boolean | undefined>;
    /**
     * Whether the user can modify account payment methods.
     */
    public readonly accountManagePaymentMethods!: pulumi.Output<boolean | undefined>;
    /**
     * **Deprecated** Whether the user can modify the account plan.
     *
     * @deprecated obsolete, should no longer be used
     */
    public readonly accountManagePlan!: pulumi.Output<boolean | undefined>;
    /**
     * Whether the user can modify other teams in the account.
     */
    public readonly accountManageTeams!: pulumi.Output<boolean | undefined>;
    /**
     * Whether the user can modify account users.
     */
    public readonly accountManageUsers!: pulumi.Output<boolean | undefined>;
    /**
     * Whether the user can view activity logs.
     */
    public readonly accountViewActivityLog!: pulumi.Output<boolean | undefined>;
    /**
     * Whether the user can view invoices.
     */
    public readonly accountViewInvoices!: pulumi.Output<boolean | undefined>;
    /**
     * Whether the user can modify data feeds.
     */
    public readonly dataManageDatafeeds!: pulumi.Output<boolean | undefined>;
    /**
     * Whether the user can modify data sources.
     */
    public readonly dataManageDatasources!: pulumi.Output<boolean | undefined>;
    /**
     * Whether the user can publish to data feeds.
     */
    public readonly dataPushToDatafeeds!: pulumi.Output<boolean | undefined>;
    /**
     * Whether the user can manage DHCP.
     * Only relevant for the DDI product.
     */
    public readonly dhcpManageDhcp!: pulumi.Output<boolean | undefined>;
    /**
     * Whether the user can view DHCP.
     * Only relevant for the DDI product.
     */
    public readonly dhcpViewDhcp!: pulumi.Output<boolean | undefined>;
    /**
     * Whether the user can modify the accounts zones.
     */
    public readonly dnsManageZones!: pulumi.Output<boolean | undefined>;
    /**
     * Whether the user can view the accounts zones.
     */
    public readonly dnsViewZones!: pulumi.Output<boolean | undefined>;
    /**
     * If true, enable the `dnsZonesAllow` list, otherwise enable the `dnsZonesDeny` list.
     */
    public readonly dnsZonesAllowByDefault!: pulumi.Output<boolean | undefined>;
    /**
     * List of zones that the user may access.
     */
    public readonly dnsZonesAllows!: pulumi.Output<string[] | undefined>;
    /**
     * List of zones that the user may not access.
     */
    public readonly dnsZonesDenies!: pulumi.Output<string[] | undefined>;
    /**
     * The email address of the user.
     */
    public readonly email!: pulumi.Output<string>;
    /**
     * Sets exclusivity on this IP whitelist.
     */
    public readonly ipWhitelistStrict!: pulumi.Output<boolean | undefined>;
    /**
     * The IP addresses to whitelist for this key.
     */
    public readonly ipWhitelists!: pulumi.Output<string[] | undefined>;
    /**
     * Whether the user can manage IPAM.
     * Only relevant for the DDI product.
     */
    public readonly ipamManageIpam!: pulumi.Output<boolean | undefined>;
    public readonly ipamViewIpam!: pulumi.Output<boolean | undefined>;
    /**
     * Whether the user can modify monitoring jobs.
     */
    public readonly monitoringManageJobs!: pulumi.Output<boolean | undefined>;
    /**
     * Whether the user can modify notification lists.
     */
    public readonly monitoringManageLists!: pulumi.Output<boolean | undefined>;
    /**
     * Whether the user can view monitoring jobs.
     */
    public readonly monitoringViewJobs!: pulumi.Output<boolean | undefined>;
    /**
     * The free form name of the user.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Whether or not to notify the user of specified events. Only `billing` is available currently.
     */
    public readonly notify!: pulumi.Output<{[key: string]: any} | undefined>;
    /**
     * Whether the user can manage global active directory.
     * Only relevant for the DDI product.
     */
    public readonly securityManageActiveDirectory!: pulumi.Output<boolean | undefined>;
    /**
     * Whether the user can manage global two factor authentication.
     */
    public readonly securityManageGlobal2fa!: pulumi.Output<boolean | undefined>;
    /**
     * The teams that the user belongs to.
     */
    public readonly teams!: pulumi.Output<string[] | undefined>;
    /**
     * The users login name.
     */
    public readonly username!: pulumi.Output<string>;

    /**
     * Create a User resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: UserArgs | UserState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as UserState | undefined;
            inputs["accountManageAccountSettings"] = state ? state.accountManageAccountSettings : undefined;
            inputs["accountManageApikeys"] = state ? state.accountManageApikeys : undefined;
            inputs["accountManagePaymentMethods"] = state ? state.accountManagePaymentMethods : undefined;
            inputs["accountManagePlan"] = state ? state.accountManagePlan : undefined;
            inputs["accountManageTeams"] = state ? state.accountManageTeams : undefined;
            inputs["accountManageUsers"] = state ? state.accountManageUsers : undefined;
            inputs["accountViewActivityLog"] = state ? state.accountViewActivityLog : undefined;
            inputs["accountViewInvoices"] = state ? state.accountViewInvoices : undefined;
            inputs["dataManageDatafeeds"] = state ? state.dataManageDatafeeds : undefined;
            inputs["dataManageDatasources"] = state ? state.dataManageDatasources : undefined;
            inputs["dataPushToDatafeeds"] = state ? state.dataPushToDatafeeds : undefined;
            inputs["dhcpManageDhcp"] = state ? state.dhcpManageDhcp : undefined;
            inputs["dhcpViewDhcp"] = state ? state.dhcpViewDhcp : undefined;
            inputs["dnsManageZones"] = state ? state.dnsManageZones : undefined;
            inputs["dnsViewZones"] = state ? state.dnsViewZones : undefined;
            inputs["dnsZonesAllowByDefault"] = state ? state.dnsZonesAllowByDefault : undefined;
            inputs["dnsZonesAllows"] = state ? state.dnsZonesAllows : undefined;
            inputs["dnsZonesDenies"] = state ? state.dnsZonesDenies : undefined;
            inputs["email"] = state ? state.email : undefined;
            inputs["ipWhitelistStrict"] = state ? state.ipWhitelistStrict : undefined;
            inputs["ipWhitelists"] = state ? state.ipWhitelists : undefined;
            inputs["ipamManageIpam"] = state ? state.ipamManageIpam : undefined;
            inputs["ipamViewIpam"] = state ? state.ipamViewIpam : undefined;
            inputs["monitoringManageJobs"] = state ? state.monitoringManageJobs : undefined;
            inputs["monitoringManageLists"] = state ? state.monitoringManageLists : undefined;
            inputs["monitoringViewJobs"] = state ? state.monitoringViewJobs : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["notify"] = state ? state.notify : undefined;
            inputs["securityManageActiveDirectory"] = state ? state.securityManageActiveDirectory : undefined;
            inputs["securityManageGlobal2fa"] = state ? state.securityManageGlobal2fa : undefined;
            inputs["teams"] = state ? state.teams : undefined;
            inputs["username"] = state ? state.username : undefined;
        } else {
            const args = argsOrState as UserArgs | undefined;
            if (!args || args.email === undefined) {
                throw new Error("Missing required property 'email'");
            }
            if (!args || args.username === undefined) {
                throw new Error("Missing required property 'username'");
            }
            inputs["accountManageAccountSettings"] = args ? args.accountManageAccountSettings : undefined;
            inputs["accountManageApikeys"] = args ? args.accountManageApikeys : undefined;
            inputs["accountManagePaymentMethods"] = args ? args.accountManagePaymentMethods : undefined;
            inputs["accountManagePlan"] = args ? args.accountManagePlan : undefined;
            inputs["accountManageTeams"] = args ? args.accountManageTeams : undefined;
            inputs["accountManageUsers"] = args ? args.accountManageUsers : undefined;
            inputs["accountViewActivityLog"] = args ? args.accountViewActivityLog : undefined;
            inputs["accountViewInvoices"] = args ? args.accountViewInvoices : undefined;
            inputs["dataManageDatafeeds"] = args ? args.dataManageDatafeeds : undefined;
            inputs["dataManageDatasources"] = args ? args.dataManageDatasources : undefined;
            inputs["dataPushToDatafeeds"] = args ? args.dataPushToDatafeeds : undefined;
            inputs["dhcpManageDhcp"] = args ? args.dhcpManageDhcp : undefined;
            inputs["dhcpViewDhcp"] = args ? args.dhcpViewDhcp : undefined;
            inputs["dnsManageZones"] = args ? args.dnsManageZones : undefined;
            inputs["dnsViewZones"] = args ? args.dnsViewZones : undefined;
            inputs["dnsZonesAllowByDefault"] = args ? args.dnsZonesAllowByDefault : undefined;
            inputs["dnsZonesAllows"] = args ? args.dnsZonesAllows : undefined;
            inputs["dnsZonesDenies"] = args ? args.dnsZonesDenies : undefined;
            inputs["email"] = args ? args.email : undefined;
            inputs["ipWhitelistStrict"] = args ? args.ipWhitelistStrict : undefined;
            inputs["ipWhitelists"] = args ? args.ipWhitelists : undefined;
            inputs["ipamManageIpam"] = args ? args.ipamManageIpam : undefined;
            inputs["ipamViewIpam"] = args ? args.ipamViewIpam : undefined;
            inputs["monitoringManageJobs"] = args ? args.monitoringManageJobs : undefined;
            inputs["monitoringManageLists"] = args ? args.monitoringManageLists : undefined;
            inputs["monitoringViewJobs"] = args ? args.monitoringViewJobs : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["notify"] = args ? args.notify : undefined;
            inputs["securityManageActiveDirectory"] = args ? args.securityManageActiveDirectory : undefined;
            inputs["securityManageGlobal2fa"] = args ? args.securityManageGlobal2fa : undefined;
            inputs["teams"] = args ? args.teams : undefined;
            inputs["username"] = args ? args.username : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(User.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering User resources.
 */
export interface UserState {
    /**
     * Whether the user can modify account settings.
     */
    readonly accountManageAccountSettings?: pulumi.Input<boolean>;
    /**
     * Whether the user can modify account apikeys.
     */
    readonly accountManageApikeys?: pulumi.Input<boolean>;
    /**
     * Whether the user can modify account payment methods.
     */
    readonly accountManagePaymentMethods?: pulumi.Input<boolean>;
    /**
     * **Deprecated** Whether the user can modify the account plan.
     *
     * @deprecated obsolete, should no longer be used
     */
    readonly accountManagePlan?: pulumi.Input<boolean>;
    /**
     * Whether the user can modify other teams in the account.
     */
    readonly accountManageTeams?: pulumi.Input<boolean>;
    /**
     * Whether the user can modify account users.
     */
    readonly accountManageUsers?: pulumi.Input<boolean>;
    /**
     * Whether the user can view activity logs.
     */
    readonly accountViewActivityLog?: pulumi.Input<boolean>;
    /**
     * Whether the user can view invoices.
     */
    readonly accountViewInvoices?: pulumi.Input<boolean>;
    /**
     * Whether the user can modify data feeds.
     */
    readonly dataManageDatafeeds?: pulumi.Input<boolean>;
    /**
     * Whether the user can modify data sources.
     */
    readonly dataManageDatasources?: pulumi.Input<boolean>;
    /**
     * Whether the user can publish to data feeds.
     */
    readonly dataPushToDatafeeds?: pulumi.Input<boolean>;
    /**
     * Whether the user can manage DHCP.
     * Only relevant for the DDI product.
     */
    readonly dhcpManageDhcp?: pulumi.Input<boolean>;
    /**
     * Whether the user can view DHCP.
     * Only relevant for the DDI product.
     */
    readonly dhcpViewDhcp?: pulumi.Input<boolean>;
    /**
     * Whether the user can modify the accounts zones.
     */
    readonly dnsManageZones?: pulumi.Input<boolean>;
    /**
     * Whether the user can view the accounts zones.
     */
    readonly dnsViewZones?: pulumi.Input<boolean>;
    /**
     * If true, enable the `dnsZonesAllow` list, otherwise enable the `dnsZonesDeny` list.
     */
    readonly dnsZonesAllowByDefault?: pulumi.Input<boolean>;
    /**
     * List of zones that the user may access.
     */
    readonly dnsZonesAllows?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * List of zones that the user may not access.
     */
    readonly dnsZonesDenies?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The email address of the user.
     */
    readonly email?: pulumi.Input<string>;
    /**
     * Sets exclusivity on this IP whitelist.
     */
    readonly ipWhitelistStrict?: pulumi.Input<boolean>;
    /**
     * The IP addresses to whitelist for this key.
     */
    readonly ipWhitelists?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Whether the user can manage IPAM.
     * Only relevant for the DDI product.
     */
    readonly ipamManageIpam?: pulumi.Input<boolean>;
    readonly ipamViewIpam?: pulumi.Input<boolean>;
    /**
     * Whether the user can modify monitoring jobs.
     */
    readonly monitoringManageJobs?: pulumi.Input<boolean>;
    /**
     * Whether the user can modify notification lists.
     */
    readonly monitoringManageLists?: pulumi.Input<boolean>;
    /**
     * Whether the user can view monitoring jobs.
     */
    readonly monitoringViewJobs?: pulumi.Input<boolean>;
    /**
     * The free form name of the user.
     */
    readonly name?: pulumi.Input<string>;
    /**
     * Whether or not to notify the user of specified events. Only `billing` is available currently.
     */
    readonly notify?: pulumi.Input<{[key: string]: any}>;
    /**
     * Whether the user can manage global active directory.
     * Only relevant for the DDI product.
     */
    readonly securityManageActiveDirectory?: pulumi.Input<boolean>;
    /**
     * Whether the user can manage global two factor authentication.
     */
    readonly securityManageGlobal2fa?: pulumi.Input<boolean>;
    /**
     * The teams that the user belongs to.
     */
    readonly teams?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The users login name.
     */
    readonly username?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a User resource.
 */
export interface UserArgs {
    /**
     * Whether the user can modify account settings.
     */
    readonly accountManageAccountSettings?: pulumi.Input<boolean>;
    /**
     * Whether the user can modify account apikeys.
     */
    readonly accountManageApikeys?: pulumi.Input<boolean>;
    /**
     * Whether the user can modify account payment methods.
     */
    readonly accountManagePaymentMethods?: pulumi.Input<boolean>;
    /**
     * **Deprecated** Whether the user can modify the account plan.
     *
     * @deprecated obsolete, should no longer be used
     */
    readonly accountManagePlan?: pulumi.Input<boolean>;
    /**
     * Whether the user can modify other teams in the account.
     */
    readonly accountManageTeams?: pulumi.Input<boolean>;
    /**
     * Whether the user can modify account users.
     */
    readonly accountManageUsers?: pulumi.Input<boolean>;
    /**
     * Whether the user can view activity logs.
     */
    readonly accountViewActivityLog?: pulumi.Input<boolean>;
    /**
     * Whether the user can view invoices.
     */
    readonly accountViewInvoices?: pulumi.Input<boolean>;
    /**
     * Whether the user can modify data feeds.
     */
    readonly dataManageDatafeeds?: pulumi.Input<boolean>;
    /**
     * Whether the user can modify data sources.
     */
    readonly dataManageDatasources?: pulumi.Input<boolean>;
    /**
     * Whether the user can publish to data feeds.
     */
    readonly dataPushToDatafeeds?: pulumi.Input<boolean>;
    /**
     * Whether the user can manage DHCP.
     * Only relevant for the DDI product.
     */
    readonly dhcpManageDhcp?: pulumi.Input<boolean>;
    /**
     * Whether the user can view DHCP.
     * Only relevant for the DDI product.
     */
    readonly dhcpViewDhcp?: pulumi.Input<boolean>;
    /**
     * Whether the user can modify the accounts zones.
     */
    readonly dnsManageZones?: pulumi.Input<boolean>;
    /**
     * Whether the user can view the accounts zones.
     */
    readonly dnsViewZones?: pulumi.Input<boolean>;
    /**
     * If true, enable the `dnsZonesAllow` list, otherwise enable the `dnsZonesDeny` list.
     */
    readonly dnsZonesAllowByDefault?: pulumi.Input<boolean>;
    /**
     * List of zones that the user may access.
     */
    readonly dnsZonesAllows?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * List of zones that the user may not access.
     */
    readonly dnsZonesDenies?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The email address of the user.
     */
    readonly email: pulumi.Input<string>;
    /**
     * Sets exclusivity on this IP whitelist.
     */
    readonly ipWhitelistStrict?: pulumi.Input<boolean>;
    /**
     * The IP addresses to whitelist for this key.
     */
    readonly ipWhitelists?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Whether the user can manage IPAM.
     * Only relevant for the DDI product.
     */
    readonly ipamManageIpam?: pulumi.Input<boolean>;
    readonly ipamViewIpam?: pulumi.Input<boolean>;
    /**
     * Whether the user can modify monitoring jobs.
     */
    readonly monitoringManageJobs?: pulumi.Input<boolean>;
    /**
     * Whether the user can modify notification lists.
     */
    readonly monitoringManageLists?: pulumi.Input<boolean>;
    /**
     * Whether the user can view monitoring jobs.
     */
    readonly monitoringViewJobs?: pulumi.Input<boolean>;
    /**
     * The free form name of the user.
     */
    readonly name?: pulumi.Input<string>;
    /**
     * Whether or not to notify the user of specified events. Only `billing` is available currently.
     */
    readonly notify?: pulumi.Input<{[key: string]: any}>;
    /**
     * Whether the user can manage global active directory.
     * Only relevant for the DDI product.
     */
    readonly securityManageActiveDirectory?: pulumi.Input<boolean>;
    /**
     * Whether the user can manage global two factor authentication.
     */
    readonly securityManageGlobal2fa?: pulumi.Input<boolean>;
    /**
     * The teams that the user belongs to.
     */
    readonly teams?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The users login name.
     */
    readonly username: pulumi.Input<string>;
}
